MyFirstProgram/Models/ErrorViewModel.cs
namespace MyFirstProgram.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MyFirstProgram/Models/Student.cs
namespace MyFirstProgram.Models
{
	public class Student
	{
        public int Id { get; set; }
		public string? Name { get; set;}
		public string? Email { get; set;}
		public string? Phone { get; set;}
		public string? Address { get; set;}
		
    }
}

MyFirstProgram/Models/Teacher.cs
namespace MyFirstProgram.Models
{
	public class Teacher
	{
		public int Id { get; set; }
		public string? NAme { get; set; }
        public string? Address { get; set; }
        public string? Number { get; set; }

    }
}

MyFirstProgram/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstProgram.Models;
using System.Diagnostics;

namespace MyFirstProgram.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MyFirstProgram/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using MyFirstProgram.Data;

namespace MyFirstProgram.Controllers
{
	
	public class StudentController : Controller
	{
		private ApplicationDbContext _context;
			public StudentController(ApplicationDbContext context)
		{
		     _context= context;
		}
		[HttpGet]
			public IActionResult Index()
		{
			var students= _context.Students.ToList();

			return View(students);
		}
	}
}

MyFirstProgram/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;

namespace MyFirstProgram.Controllers
{
	public class TeacherController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Distpaly()
		{
			return View();
		}
	}
}

MyFirstProgram/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyFirstProgram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstProgram</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyFirstProgram.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFirstProgram</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index" asp-action="Display">Teacher</a>
                        </li>
                    
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MyFirstProgram - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyFirstProgram/Views/Student/Index.cshtml
@model List<Student>

<h2>List of Students</h2>
<hr />
<table class="table">
	<thead>
		<tr>
			<th>
				Id
			</th>
			<th>
				Name
			</th>
			<th>
				Address
			</th>
			<th>Email</th>
			<th>Phone</th>
		</tr>
	</thead>
	<tbody>

		@foreach (var student in Model)
		{
			<tr>
				<td>@student.Id</td>
				<td>@student.Name</td>
				<td>@student.Address</td>
				<td>@student.Email</td>
				<td>@student.Phone</td>
			</tr>
		}


	</tbody>
</table>

MyFirstProgram/Views/Teacher/Display.cshtml
<h2> Hello this is the page of Teachers</h2>
<h1> Please go back</h1>

MyFirstProgram/Views/Teacher/Index.cshtml
<h2>List of teachers </h2>
<hr />
<table class="table">
	<thead>
		<tr>
			<th>SN.</th>
			<th>Name.</th>
			<th>Address.</th>
			<th>Number.</th>
			
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>1.</td>
			<td>Sumit</td>
			<td>Birtamode</td>
			<td>9824074637</td>
		</tr>
	</tbody>
</table>